FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


FROM node:22-alpine AS runner

ENV NODE_ENV=production

WORKDIR /app

RUN chown node:node /app

USER node

COPY package*.json ./
RUN npm ci --only=production

COPY --from=builder --chown=node:node /app/dist ./dist
EXPOSE 3000

CMD ["node", "dist/main.js"]